### ISSUE TITLE
Add the Value {ProfileName}

### ISSUE THREAD

**Issue by cocker-cc** [hrvojesolc/Custom-Titlebar-Text#11]
Hi, Hrvoje, 
please add the Value `{ProfileName}` to the List of avaliable Values.
Thanks for Your Work
– Cocker :wq

**Comment by JavaScriptDude** [comment]
I have not dug too deep but this may no longer be possible due to security restrictions added a while back. The workaround is to add a unique string to identify the profile. Since each profile has its own configuration settings, you can uniquely identify each one easily.

**Comment by hr3x8** [comment]
This add-on is now defunct.
