### ISSUE TITLE
Req: version for Thunderbird

### ISSUE THREAD

**Issue by Frank-Steiner** [hrvojesolc/Custom-Titlebar-Text#12]
Hi,
thanks a lot for this addon, I'm quite happy to get rid of the page title in the title bar finally :)

I wonder how difficult it would be to release the same addon for Thunderbird? Just being able to enter a custom string (without any variables) would already help a lot. 

cu,
Frank

**Comment by hr3x8** [comment]
This add-on is now defunct.
