### ISSUE TITLE
Not working for empty tabs

### ISSUE THREAD

**Issue by Frank-Steiner** [hrvojesolc/Custom-Titlebar-Text#13]
Hi,
if the active tab is empty (= tab title "New Tab"), then the title will show "New Tab" instead of the custom string. And funnily, the same happens for this page here, it shows "New Issue ... (etc)" instead of the custom string. Just like page titles starting with "New" don't work?!

cu,
Frank

**Comment by hr3x8** [comment]
This add-on is now defunct.
