### ISSUE TITLE
Add title the tab that is playing audio (or YouTube)

### ISSUE THREAD

**Issue by techtonik** [hrvojesolc/Custom-Titlebar-Text#15]
I am looking for an extension to show the title of currently played YouTube video. So basically I want to read the title of the middle tab here and show it as window title. I wonder if it is possible to add this functionality to this extension?

![image](https://user-images.githubusercontent.com/515889/48972544-8d5aa780-f03d-11e8-8afc-e5c888943ee8.png)

**Comment by techtonik** [comment]
It is possible to get first audible tab and get its title https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/tabs/query as `{FirstAudibleTabTitle}`.

**Comment by hr3x8** [comment]
This add-on is now defunct.
