### ISSUE TITLE
title not actually the title

### ISSUE THREAD

**Issue by 5x3** [hrvojesolc/Custom-Titlebar-Text#16]
I use Nightly Tester Tools for older FF (linux).
they change real FF title (open new tab and it would be my custom title)
your plugin change the name of the tab, if you open new tab - custom title dissapears.
my custom sting in EVERY tab i opened - WHF?
can you fix it, and implement title change in a right way?

Also
They have ${profile} with dir of FF profile - very useful.

**Comment by hr3x8** [comment]
This add-on is now defunct.
