### ISSUE TITLE
Features fom v2.08  missing in ver 2.1.7 

### ISSUE THREAD

**Issue by dapgo** [hrvojesolc/Custom-Titlebar-Text#8]
I see that current version (2.1.7) has less option in the menu than previous version 2.0.8
I tried entering manually a variables ({platformVersion}) but it doesn't work.
Also in FF47, the addon doesn't show the option button.

However old version 2.08 works fine in most Firefox versions, at least in v27, v47, and WF55 (so supposedly it will work on FF55)

**Comment by hr3x8** [comment]
Hello dapgo,

Version 0.2.1.7 is different add-on than 2.0.8. Version 0.2.1.7 is written using Web Extensions API for Firefox version 55+. New version is using Web Extensions API that shows preferences in-line and not as a pop-up. I haven't tested with anything less that FF55 for new add-on.

Old version 2.0.8 stopped working for me few months back and hence I made a new one from scratch using new Web Extensions API. New API is currently rather limited, hence less options than the previous one. Once you upgrade to FF55+, try this add-on.

I've mistakenly hidden 2.0.8 from the add-on list and wasn't able to un-hide it afterwards. I've put the old version 2.0.8 on github here https://github.com/hrvojesolc/Custom-Titlebar-Text/blob/legacy/legacy/customize_titlebar_v2-0.8-fx.xpi. You can try installing it manually for old versions of Firefox. I have no plans on supporting older versions. Hope this helps.

Kind regards,

Hrvoje

**Comment by dapgo** [comment]
Thanks Man!
My plan is do not move to Firefox 57 or above. Just move to updated Firefox engines through Palemoon and Waterfox because both will keep support for XUL extensions. In fact Waterfox will support webextensions and XUL :)

**Comment by Gittyperson** [comment]
Many thanks for your very nice extension! About 2.0.8, I hope you can consider uploading it to the [Pale Moon Add-ons Site](https://addons.palemoon.org/) where it can live on, since it works just fine with PM. Some more info [here](http://developer.palemoon.org/Add-ons:Site).
